#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  backRightEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  frontRightEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  frontLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  backLeftEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  winchEncoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  liftEncdoder,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_7,  leftClawEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_8,  rightClawEncoder, sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port3,           winch,         tmotorVex393_MC29, openLoop, encoderPort, I2C_5)
#pragma config(Motor,  port4,           topLeftLift,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_6)
#pragma config(Motor,  port5,           leftClaw,      tmotorVex393_MC29, openLoop, encoderPort, I2C_7)
#pragma config(Motor,  port6,           rightClaw,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_8)
#pragma config(Motor,  port7,           topRightLift,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           bottomRightLift, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           frontLeft,     tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          frontRight,    tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: This is the code for 479C Mk2                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#define TPR 627

/*---------------------------------------------------------------------------*/
/*                             Helper Funcitons                              */
/*                                                                           */
/* These functions are present to assist limit code reuse and make           */
/* programming autonomous much easier.                                       */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// Absolute value function
#define abs(X) ((X < 0) ? -1 * X : X)

#define LCD_LEFT 1
#define LCD_MID 2
#define LCD_RIGHT 4

#define LCD_MENU_STRING "<    SELECT    >"
#define AUTO_COUNT 5

bool winch1 = false;
bool winch2 = false;
bool winch3 = false;

short autoMode = 0;

string autoModeNames[] = {"No autonomous", "15 Second Right", "15 Second Left", "60 Second Right", "60 Second Left"};

void driveForward(int speed){
	motor[backLeft] = speed;
	motor[backRight] = speed;
	motor[frontLeft] = speed;
	motor[frontRight] = speed;
}


// Positive values turn clockwise
void turn(int speed){
	motor[backLeft] = speed;
	motor[backRight] = -speed;
	motor[frontLeft] = speed;
	motor[frontRight] = -speed;
}

void lift(int speed){
	motor[topLeftLift] = speed;
	motor[bottomRightLift] = speed;
	motor[topRightLift] = speed;
}

void claw(int speed){
	motor[leftClaw] = speed;
	motor[rightClaw] = speed;
}

// Turns the winch to remove slack in preperation for lift
void removeSlackFronWinch(){
	if(winch3){
		if(!winch1){
			winch1 = true;
			motor[winch] = 127;
			resetMotorEncoder(winch);
		}
		if(getMotorEncoder(winch) >= 2565){
			motor[winch] = 0;
			winch1 = false;
			winch3 = false;
		}
	}

}

void climb() {
	winch2 = true;
	SensorValue[winchEncoder] = 0;
	motor[winch] = 127;
	untilEncoderCounts(14000, winchEncoder);
	motor[winch] = 0;
	winch2 = false;
}

void autonMenu(){
	bLCDBacklight = true;
	short index = 0;
	short buttons = 0;
	short lastButtons = 0;
	bool first = true;

	displayLCDCenteredString(0, autoModeNames[index]);
	displayLCDCenteredString(1, LCD_MENU_STRING);

	while((buttons != LCD_MID || first)  && bIfiRobotDisabled){
		buttons = nLCDButtons;
		first = false;
		writeDebugStreamLine("Buttons are : %i", buttons);
		if(buttons != 0 && lastButtons == 0){
			if(buttons == LCD_MID){
				autoMode = index;
				clearLCDLine(1);
			} else {
				if(buttons == LCD_LEFT){
					index--;
				} else if(buttons == LCD_RIGHT){
					index++;
				}
				if(index < 0) index = AUTO_COUNT - 1;
				if(index >= AUTO_COUNT) index = 0;
				clearLCDLine(0);
				displayLCDCenteredString(0, autoModeNames[index]);
			}
		}
		lastButtons = buttons;
	}
}

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	bDisplayCompetitionStatusOnLcd = false;

	autonMenu();

	bLCDBacklight = false;
	if(bIfiRobotDisabled){
		displayLCDCenteredString(1, "BACK");
	  short lastButtons = nLCDButtons;
		while(bIfiRobotDisabled) {
			if(nLCDButtons == LCD_MID && lastButtons == 0){
				autonMenu();
			}
			lastButtons = nLCDButtons;
		}

	}

	clearLCDLine(1);

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

// Drive at speed for time
void driveForwardFor(int speed, float time) {
	driveForward(speed);
  sleep(time);
  driveForward(0);
}

// Turn at speed for time
void turnFor(int speed, float time) {
	turn(speed);
  sleep(time);
  turn(0);
}

// Move claw at speed for time
void moveClawFor(int speed, float time) {
	claw(speed);
  sleep(time);
  claw(0);
}

// Move arm at speed for time
void moveArmFor(int speed, float time) {
	lift(speed);
	sleep(time);
	claw(0);
}


/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

void auto15R(){
	moveClawFor(127, 1.5); // Close claw around preload
  driveForwardFor(127, 1.5); // Drive forward to line
  turnFor(127, 1.5); // Turn 180 degres
  driveForwardFor(-127, 1.5); // Drive backward to fence
  moveArmFor(127, 1.5); // Lift arm to throw star over fence
	moveClawFor(-127, 1.5); // Open claw a little bit
  moveClawFor(127, 1.5); // Close claw forward
  moveArmFor(-127, 1.5); // Lower arm
  moveClawFor(-127, 1.5); // Retract claw
  moveArmFor(127, 1.5); // Lift arm
  moveClawFor(127, 1.5); // Close claw part of the way
  moveArmFor(-127, 1.5); // Lower arm
  driveForwardFor(127, 1.5); // Drive forward to midline
  turnFor(127, 1.5); // Turn toward cube
  driveForwardFor(127, 1.5); // Drive to cube
  moveClawFor(127, 1.5); // Grab cube
  turnFor(-127, 1.5); // Turn away from fence
  driveForwardFor(127, 1.5); // Reverse into fence
  moveArmFor(127, 1.5); // Lift arm to throw cube over fence
	moveClawFor(-127, 1.5); // Open claw a little bit
  moveClawFor(127, 1.5); // Close claw forward
  moveArmFor(-127, 1.5); // Lower arm
  moveClawFor(-127, 1.5); // Retract claw
  moveArmFor(127, 1.5); // Lift arm
  moveClawFor(127, 1.5); // Close claw part of the way
  moveArmFor(-127, 1.5); // Lower arm
}

void auto15L(){
	moveClawFor(127, 1.5); // Close claw around preload
  driveForwardFor(127, 1.5); // Drive forward to line
  turnFor(127, 1.5); // Turn 180 degres
  driveForwardFor(-127, 1.5); // Drive backward to fence
  moveArmFor(127, 1.5); // Lift arm to throw star over fence
	moveClawFor(-127, 1.5); // Open claw a little bit
  moveClawFor(127, 1.5); // Close claw forward
  moveArmFor(-127, 1.5); // Lower arm
  moveClawFor(-127, 1.5); // Retract claw
  moveArmFor(127, 1.5); // Lift arm
  moveClawFor(127, 1.5); // Close claw part of the way
  moveArmFor(-127, 1.5); // Lower arm
  driveForwardFor(127, 1.5); // Drive forward to midline
  turnFor(-127, 1.5); // Turn toward cube
  driveForwardFor(127, 1.5); // Drive to cube
  moveClawFor(127, 1.5); // Grab cube
  turnFor(127, 1.5); // Turn away from fence
  driveForwardFor(127, 1.5); // Reverse into fence
  moveArmFor(127, 1.5); // Lift arm to throw cube over fence
	moveClawFor(-127, 1.5); // Open claw a little bit
  moveClawFor(127, 1.5); // Close claw forward
  moveArmFor(-127, 1.5); // Lower arm
  moveClawFor(-127, 1.5); // Retract claw
  moveArmFor(127, 1.5); // Lift arm
  moveClawFor(127, 1.5); // Close claw part of the way
  moveArmFor(-127, 1.5); // Lower arm
}

void auto60R(){
	auto15R();

}

void auto60L(){
	auto15L();
}

task autonomous()
{
  switch(autoMode){
  	case 1:
  		auto15R();
  		break;
  	case 2:
  		auto15L();
  		break;
  	case 3:
  		auto60R();
  		break;
  	case 4:
  		auto60L();
  		break;
  }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    //holonomic drive*..
   	motor[frontLeft] = vexRT[Ch4] + vexRT[Ch1] + vexRT[Ch3];
   	motor[frontRight] = -vexRT[Ch4] - vexRT[Ch1] + vexRT[Ch3];
   	motor[backLeft] = -vexRT[Ch4] + vexRT[Ch1] + vexRT[Ch3];
   	motor[backRight] = vexRT[Ch4] -  vexRT[Ch1] + vexRT[Ch3];

   	if(vexRT(Btn5UXmtr2)){
	  	lift(127);
		} else if(vexRT(Btn5DXmtr2)){
			lift(-127);
		} else {
			lift(0);
		}

		if(vexRT(Btn6UXmtr2)){
			claw(127);
		} else if(vexRT(Btn6DXmtr2)){
			claw(-127);
		} else {
			claw(0);
		}

		if(vexRT(Btn7L) || vexRT(Btn8L) || vexRT(Btn7LXmtr2) || vexRT(Btn8LXmtr2)) {
			motor[winch] = 127;
		} else if(vexRT(Btn7D) && vexRT(Btn7DXmtr2)) {
			motor[winch] = -127;
		} else if(!winch3) {
			motor[winch] = 0;
		}

		if(vexRT(Btn7U) && vexRT(Btn7UXmtr2) && !winch1 && !winch2){
			winch3 = true;
		}

		if(vexRT(Btn8U) && vexRT(Btn8UXmtr2) && !winch1 && !winch2){
			climb();
		}
		removeSlackFronWinch();
  }
}
